---
# tasks file for gce-instance
- name: create a disk
  gcp_compute_disk:
    name: "{{ vm_name }}"
    size_gb: 10
    source_image: "{{ image }}"
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute
    state: present
  register: disk
- name: create network
  gcp_compute_network:
    name: 'default'
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute
    state: present
  register: network
- name: create a address
  gcp_compute_address:
    name: "{{ vm_name }}"
    region: "{{ region }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute
    state: present
  register: address
- name: open firewall
  gcp_compute_firewall:
    name: docker-port
    allowed:
    - ip_protocol: tcp
      ports:
      - '2375'
      - '2377'
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
- name: create instance
  gcp_compute_instance:
    state: present
    name: "{{ vm_name }}"
    machine_type: f1-micro
    disks:
      - auto_delete: true
        boot: true
        source: "{{ disk }}"
    network_interfaces:
      - network: "{{ network }}"
        access_configs:
          - name: 'External NAT'
            nat_ip: "{{ address }}"
            type: 'ONE_TO_ONE_NAT'
    zone: "{{ zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    scopes:
      - https://www.googleapis.com/auth/compute
  register: instance
- name: Wait for SSH to come up
  wait_for: host={{ address.address }} port=22 delay=10 timeout=60
- set_fact:
    host_ip: "{{ address.address }}"
