- name: Create an instance
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    gcp_project: round-plating-286915
    gcp_cred_kind: serviceaccount
    gcp_cred_file: /Users/michaelschmidt/git/techchallenge/round-plating-286915-49944854916b.json
    zone: "us-central1-b"
    region: "us-central1"
    image: "https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/debian-9-stretch-v20180911"

  tasks:

    - name: delete the instance
      gcp_compute_instance:
        state: absent
        name: test-vm
        machine_type: n1-standard-1
        zone: "{{ zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes:
          - https://www.googleapis.com/auth/compute
      register: instance
